import type { Metadata } from "next";
import {  Outfit } from "next/font/google";
import "./globals.css";
import Header from "./components/homePageComp/Header";
import Footer from "./components/homePageComp/Footer";
import { AuthProvider } from "./context/AuthContext";

const outfit = Outfit({
  weight: ["400", "700"],
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${outfit.style} antialiased`}>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
