import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "./context/AuthContext";
import { CartProvider } from "./context/CartContext";
import { OrderProvider } from "./context/OrderContext";
import { ProductProvider } from "./context/ProductContext";
import LayoutWrapper from "./components/LayoutWrapper";

const outfit = Outfit({
  weight: ["400", "700"],
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${outfit.style} antialiased`}>
        <AuthProvider>
          <CartProvider>
            <OrderProvider>
              <ProductProvider>
                <LayoutWrapper>{children}</LayoutWrapper>
              </ProductProvider>
            </OrderProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
